name = "FermionicMagic"
uuid = "8703e7a7-7bfb-467c-89f2-4bca801e3005"
authors = ["Yusheng Zhao <yushengzhao2020@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TopologicalNumbers = "82b459e2-751c-486c-8b84-4a85e9d7ad51"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
