#+TITLE: Fermionic Magic Research
#+AUTHOR: Yusheng Zhao && Chengkai Zhu
#+DATE: <2024-02-25 Sun>

* Question
** Why were others interested initially?
- [[http://www.physics.usyd.edu.au/quantum/Coogee2020/Presentations/Jozsa.pdf][Slides]]

  What about the qip talks

  https://www.quantamagazine.org/the-quest-to-quantify-quantumness-20231019/
** QIP 2024
*** Talks
Classical simulation of non-Gaussian fermionic circuits: Beatriz Cardoso Dias and Robert Koenig.

* Motivation
** For Others
*** All pure fermionic non–Gaussian states are magic states for matchgate computations
Presumably, quantum computation is more powerful thant classical ones because it
can provide certain "quantum-resources". In the NISQ era, where such provided
resources are limited, we must use them economically in order to gain the most
use out of quantum computers.

One kind of such quantum resource is known as "magic". It originates from
Clifford circuits, a class of classically efficiently simulatable quantum
circuits. Clifford circuits are comprised of Clifford gates. When Clifford gates
and adaptive measurements are supplied with magic states, we retrieve universal
quantum computation. In this paper, they focus on a different kind of magic
known as fermionic magic. The concept is similar, you only replace the clifford
circuits with Matchgate circuits. Matchgate circuits are those that are created
by matchgates. The reason for considering such variant is that states preparable
by matchgates circuits are those that correspond to non-interaction fermion
states. Therefore, these states can be interpreted physically more directly.

*** Classical simulation of non-Gaussian fermionic circuits
*** Improved simulation of quantum circuits dominated by free fermionic operations
** For Me
It is often asked what are the some of the most important applications of a
quantum computer. Embarrassingly, the answer is a short one. Currently, the only
quantum algorithm that provides exponential speed up comparing to the classical
counter-part is Shor's algorithm. Making things even worse, Shor's algorithm
does not solve any problem, it poses more problem in the sense that it will
destroy an encryption system that is working.

In response to this, we are looking for a new quantum algorithm that can solve
practically useful problems. Finding such an algorithm is not an easy task,
especially when we don't know what IS the difference between classical and
quantum computing. Therefore, we will have the motivation of understanding what
makes a quantum circuit hard to simulate. More specifically, we will have the
motivation of understanind it in the setting of fermionic quantum circuits.

* Goal
Implement algorithms for classically simulating fermoinic quantum circuits. This
could be done in many different ways, including but not limited to, using
ZW-Calculus, algorithms mentioned in paper.

* Time-line

* References
-
