#+TITLE: Fermionic Magic Research
#+AUTHOR: Yusheng Zhao && Chengkai Zhu
#+DATE: <2024-02-25 Sun>

* Motivation
** For Others
*** All pure fermionic non–Gaussian states are magic states for matchgate computations
Presumably, quantum computation is more powerful thant classical ones because it
can provide certain "quantum-resources". In the NISQ era, where such provided
resources are limited, we must use them economically in order to gain the most
use out of quantum computers.

One kind of such quantum resource is known as "magic". It originates from
Clifford circuits, a class of classically efficiently simulatable quantum
circuits. Clifford circuits are comprised of Clifford gates. When Clifford gates
and adaptive measurements are supplied with magic states, we retrieve universal
quantum computation. In this paper, they focus on a different kind of magic
known as fermionic magic. The concept is similar, you only replace the clifford
circuits with Matchgate circuits. Matchgate circuits are those that are created
by matchgates. The reason for considering such variant is that states preparable
by matchgates circuits are those that correspond to non-interaction fermion
states. Therefore, these states can be interpreted physically more directly.
**** Resources
- [[http://www.physics.usyd.edu.au/quantum/Coogee2020/Presentations/Jozsa.pdf][Slides]]

*** Classical simulation of non-Gaussian fermionic circuits
This contains algorithm for simulating Gaussian or non-Gaussian fermionic
circuits. Realizing the algorithm seems like merely a muscle workout.

**** Resources
There is a QIP 2024 talk: Classical simulation of non-Gaussian fermionic
circuits: Beatriz Cardoso Dias and Robert Koenig. Unfortunately, there's no
recording just yet.


*** Improved simulation of quantum circuits dominated by free fermionic operations
This too.

*** Quanta Magazine Entry
  https://www.quantamagazine.org/the-quest-to-quantify-quantumness-20231019/
** For Me
It is often asked what are the some of the most important applications of a
quantum computer. Embarrassingly, the answer is a short one. Currently, the only
quantum algorithm that provides exponential speed up comparing to the classical
counter-part is Shor's algorithm. Making things even worse, Shor's algorithm
does not solve any problem, it poses more problem in the sense that it will
destroy an encryption system that is working.

In response to this, we are looking for a new quantum algorithm that can solve
practically useful problems. Finding such an algorithm is not an easy task,
especially when we don't know what IS the difference between classical and
quantum computing. Therefore, we will have the motivation of understanding what
makes a quantum circuit hard to simulate. More specifically, we will have the
motivation of understanind it in the setting of fermionic quantum circuits.

* Goal
Implement algorithms for classically simulating fermoinic quantum circuits. This
could be done in many different ways, including but not limited to, using
ZW-Calculus, algorithms mentioned in paper. This could make way for the later
investigation of this area.

* Potential Ideas?
Besides the implementation of an efficient simulator, we need to think about
ideas or questions that utilize such simulator.

- https://arxiv.org/pdf/2402.18665.pdf
- "Here a density operator is called convex-Gaussian if it is a convex
  combination of fermionic Gaussian states. The utility of this concept was
  illustrated in [31] by showing a converse to the fault-tolerance threshold
  theorem: Sufficiently noisy quantum circuits can be simulated classically
  because the corresponding states turn out to be convex-Gaussian. A detailed
  characteriziation of convex-Gaussianity is necessary to translate this into
  explicit (numerical) threshold estimates. An infinite hierarchy of
  semidefinite programs was constructed in [31] to detect convex-Gaussianity,
  and this was subsequently shown to be complete [44]. This hierarchy also
  provides a way of determining whether a state is close to being
  convex-Gaussian"
- [[https://arxiv.org/abs/2204.12051][Sensitivity]] and how does it relate to magic and give quantum advantage
- [[https://www.semanticscholar.org/reader/5b06f89e5c4854e291aef2522a670b8bb00acafd][Trainability]] hints classical simulatability in terms of barren plateau

** More
We can follow this [[https://www.connectedpapers.com/main/254a94aa88d2a42cbdf03af6c0520020356ee9d1/graph?utm_source=share_popup&utm_medium=copy_link&utm_campaign=share_graph][link]] and paper in it. (This link focus on the first paper)

We can also follow this [[https://www.connectedpapers.com/main/94aef4b3f4da51a317257b710029e58e9e09fdfb+45a1272b0b318895d98825f5aa024eeaac8dcb06+ba3e7896a19e4a8722d512a04309d8d8d84ae3a0/graph?utm_source=share_popup&utm_medium=copy_link&utm_campaign=share_graph][link]] this graph focuses on all three paper.
* Time-line

???

* References
